# Generated by Django 3.2.18 on 2023-02-28 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_choice_is_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='percentage',
        ),
        migrations.AddField(
            model_name='match',
            name='percentage1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='percentage2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='percentage3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='user3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
