# Generated by Django 3.2.18 on 2023-02-28 19:01

from datetime import timezone
from django.db import migrations, models
from django.utils import timezone

def add_created_at(apps, schema_editor):
    Match = apps.get_model('account', 'Match')
    for match in Match.objects.all():
        match.created_at = timezone.now()
        match.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20230228_0926'),
    ]

    operations = [
        migrations.AddField(
        model_name='match',
        name='created_at',
        field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunPython(add_created_at),
    ]
