# Generated by Django 3.2.18 on 2023-02-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_match_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_match',
            field=models.BooleanField(default=False),
        ),
    ]
